services:
  postgres:
    image: postgres:15
    container_name: bun-auth-postgres
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
